language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c "create user Docker with password '123';" -U postgres
  - psql -c "create database SharkTeam;" -U postgres
  - psql -c "grant all on database SharkTeam to Docker;" -U postgres

sudo: required

branches:
  only:
  - master


